### ISSUE TITLE
Quickstart Script Doesn't Run Container on different architectures

### ISSUE THREAD

**Issue by SixBitProxyWax** [terminusdb/terminusdb-quickstart#4]
I cloned the repository and navigated to the directory as described in the README. Executing the script with *run* causes the image to be downloaded as expected and I am *told* that the server is now running. However, if I immediately execute **docker ps** there are no containers running. If I execute **docker ps -a** there are no terminus containers listed.

**To Reproduce**
1. Clone repository
2. **cd** into the repo
3. execute the script with **run**
4. check **docker ps**

**System information (please complete the following information):**
 - OS: Ubuntu
 - Version 20.04
 - How did you run terminus-quickstart? Exactly like the instructions say

**Additional context**
- Running on Raspberry Pi 4
- Connecting to the Pi via ssh

**Comment by rrooij** [comment]
This is caused by TerminusDB not having a aarch64 image yet. I keep this issue open since the quickstart script should give you a warning of some kind.

**Comment by rrooij** [comment]
The script now gives a warning when the `terminus-container` script runs on a different CPU architecture than x86_64, as there are no images for other platforms yet.

**Comment by SixBitProxyWax** [comment]
Would I be able to build from source, or is there a fundamental limitation to some dependency or something that would make that impossible?

**Comment by rrooij** [comment]
@SixBitProxyWax You can build from source. It's just that we haven't tested ARM64 that well, so unexpected problems may arise.
