### ISSUE TITLE
Inconsistent naming terminus-server vs. terminusdb-server

### ISSUE THREAD

**Issue by annainfo** [terminusdb/terminusdb-quickstart#9]
The about section contains the text "Quickstart for running the terminus-server as a docker container", but there is only https://github.com/terminusdb/terminusdb-server, no https://github.com/terminusdb/terminus-server

**Comment by 1oglop1** [comment]
Hello @annainfo since this is your first issue it seems to be a great start to contribute back to this project.
I'd recommend you to fork it, fix the issue and create PullRequest.

**Comment by annainfo** [comment]
> Hello @annainfo since this is your first issue
is that so?

> it seems
to whom?

> to be a great start
start of what?

> to contribute back to this project.
once more? why "back", did that project contribute to "me"?

> I'd recommend you to fork it, 
why?

> fix the issue 
which?

> and create PullRequest.
why?

**Comment by rrooij** [comment]
I changed the about section. Thanks for letting us know!
